calitexas<-read.csv("C:/Users/Sujit pc/Desktop/R/TimeSeriesForecasting/california texas.csv",header = TRUE,stringsAsFactors = FALSE)
str(calitexas)
calitexas$MonthYear<-as.Date(calitexas$MonthYear)
calitexasts<-ts(calitexas$Count.of.Orders,frequency = 12,start = c(2008,01,01),end = c(2012,12,01))
plot(calitexasts)
auto.arima(calitexasts,ic="bic")
calitexastsds1<-diff(calitexasts,differences = 1)
plot(calitexastsds1)
calitexastsds1arima<-arima(calitexastsds1,order = c(0,1,0))
acf(calitexastsds1arima,lag.max = 20)
calitexastsds1arima
library(forecast)
calitexastsds1arimaforecast<-forecast.Arima(calitexastsds1arima,h=12)
acf(calitexastsds1arimaforecast$residuals,lag.max = 20)
plot(calitexastsds1arimaforecast$residuals)
plot(calitexastsds1arimaforecast)
write.csv(calitexastsds1arimaforecast,file="calitexasarimaforecast.csv",row.names = FALSE)
getwd()

calitexastsds1arima1<-auto.arima(calitexastsds1,ic="bic")
calitexastsds1arimaforecast1<-forecast.Arima(calitexastsds1arima1,h=12)
acf(calitexastsds1arimaforecast1$residuals,lag.max = 20)
Box.test(calitexastsds1arimaforecast1$residuals,lag=20, type="Ljung-Box")
Box.test(calitexastsds1arimaforecast$residuals,lag=20, type="Ljung-Box")
