cosmeticData <- read.csv("C:/Users/Sujit pc/Desktop/R/CosmeticsData.csv",stringsAsFactors = FALSE,header = TRUE)
str(cosmeticData)
cosmeticData <- na.omit(cosmeticData)
install.packages("arulesViz")
library(arulesViz)
fitasso <- apriori(cosmeticData)
inspect(fitasso)
plot(fitasso)
plot(fitasso, method="graph", control=list(type="items"))
plot(fitasso, method="paracoord", control=list(reorder=TRUE))
